// Generated by https://quicktype.io

export interface GetTicketsFromDB {
  id: number;
  tickets: Ticket[];
  worker: Worker;
}

export interface Ticket {
  id: number;
  Team: Team;
  cluster: string;
  ticket_status: TicketStatus;
  ticket_category: TicketCategory;
  appointment_date: null;
  visiting_hours: null;
  customer: Customer;
  ticket_created_at: string;
  recurrent: number;
  order_id: number;
  Ticket_history: TicketHistory[];
}

export interface Team {
  id: number;
  name: Name;
}

export enum Name {
  ESandoval = 'E-Sandoval',
  St05 = 'ST-05',
  St07 = 'ST-07',
  St08 = 'ST-08',
  St10 = 'ST-10',
  St13 = 'ST-13',
  St14 = 'ST-14',
}

export interface TicketHistory {
  ticket_id: number;
  ticket_status: TicketStatus;
  description: Description;
  createdAt: string;
}

export enum Description {
  CreaciónDeOrdenDeTrabajo = 'Creación de orden de trabajo.',
}

export enum TicketStatus {
  Pendiente = 'PENDIENTE',
}

export interface Customer {
  code: number;
  name: string;
  plan: string;
  phone: Phone;
  phone2: string;
  phone3: string;
  phone4: string;
  address: string;
  geocode: Geocode;
  lastname: string;
  customer_id: number;
}

export interface Geocode {
  latitude: string;
  longitude: string;
}

export enum Phone {
  Empty = '',
  The2614241616 = '2614241616',
  The2614281661 = '2614281661',
  The2614283081 = '2614283081',
  The2614287777 = '2614287777',
  The2614448040 = '2614448040',
  The2614525874 = '2614525874',
  The2614527547 = '2614527547',
  The2614811628 = '2614811628',
  The2614900290 = '2614900290',
  The2614984007 = '2614984007',
  The2615386278 = '2615386278',
}

export enum TicketCategory {
  CambioDeVelocidadFibra = 'CAMBIO DE VELOCIDAD FIBRA',
  ClientePideTécnico = 'CLIENTE PIDE TÉCNICO',
  MejorarValores = 'MEJORAR VALORES',
  Preventivo = 'PREVENTIVO',
  PreventivoLujan = 'PREVENTIVO LUJAN',
  Redireccionar = 'REDIRECCIONAR',
  SinInternetSantaTeresita = 'SIN INTERNET - SANTA TERESITA',
  WifiHome = 'WIFI HOME',
}

export interface Worker {
  worker_id: number;
  username: string;
  name: string;
}
