export type IconType =
  | 'AiFillCar'
  | 'AiFillCalendar'
  | 'AiFillPushpin'
  | 'RiHistoryLine'
  | 'RiTodoFill'
  | 'RiDashboardFill'
  | 'RiRoadMapLine'
  | 'BsCardList'
  | 'BsFillPersonLinesFill'
  | 'BsFillTicketFill'
  | 'BsJournals'
  | 'BsSearch'
  | 'BsTelephoneFill'
  | 'BsTelephonePlusFill'
  | 'IoMapSharp'
  | 'GiPapers';
